### ISSUE TITLE
polyclone haplotype relative abundance 

### ISSUE THREAD

**Issue by slhogle** [luntergroup/octopus#127]
Hi,

Thanks for the nice software. I've been using Octopus for microbial samples in polyclone mode so far with good success. I have two questions that I couldn't find an answer for either in the preprint or here in the documentation.

1. In polyclone mode Is it possible to estimate relative abundances of haplotypes (ie strains) from the data? For example, for three haplotypes A, B, and C could you say something like A is 60%, B is 10%, and C is 30%? I see that you can get the allele frequency (AF field) in the VCF for each allele but I was wondering if there was a way to summarize this for the inferred haplotypes.

2. My samples are longitudinal from an experimental evolution timecourse so I expect to see temporal correlation between allele frequencies. Is it possible to call variants on multiple samples simultaneously and to use the temporal nature of the dataset to inform the variant calls?

Thanks for your help!
-shane

**Comment by bredelings** [comment]
I'd be interested in this as well.  We are studying reads from malaria, and its possible for a person to be infected by multiple strains so that the frequencies in the blood are e.g. 60%, 30%, 10%.  In this case, it would be very useful for us to get out the mixture frequencies.

When I read the documentation, it sounded like octopus was was using mixture proportions like this internally.  However, I wonder if octopus actually constructs global mixture proportions.

Note that it might be possible to use something like DEploid to deconvolute your reads after running octopus (https://github.com/DEploid-dev/DEploid).

**Comment by dancooke** [comment]
@slhogle `HPC` and `MAP_HF` annotations added to non-haploid polyclone calls in e04bc66c2718acc0b94a4f63f09453812f0c4dc9.
