### ISSUE TITLE
Settings for highly homozygous GBS data.

### ISSUE THREAD

**Issue by DiDeoxy** [luntergroup/octopus#135]
Hi,

I am working with GBS Barley data, barley is an inbred crop species and is therefor highly homozygous.

Do you have any recommendations for the settings for Octopus for such data?

Thanks,

Max H.

**Comment by dancooke** [comment]
Hi Max,

There's no inbreeding parameter in Octopus currently. What's the diversity like? You could adjust the [`--snp-heterozygosity`](https://github.com/luntergroup/octopus/wiki/Command-line-reference#option---snp-heterozygosity) and [`--indel-heterozygosity`](https://github.com/luntergroup/octopus/wiki/Command-line-reference#option---indel-heterozygosity) parameters if heterozygosity is far from the defaults. If heterozygosity is really high then you might need to consider adjusting other parameters like `--max-haplotypes`.

My other advice, in the absence of some good quality truth data, would be to call a sample region and use the [`--bamout`](https://github.com/luntergroup/octopus/wiki/Command-line-reference#option---bamout) option to get realigned reads. You can then view these in IGV coloured and split by the `HP` tag. This is a really nice way of visually validating what was called because ideally you should be seeing two clean haploid haplotypes. See [this wiki page](https://github.com/luntergroup/octopus/wiki/How-to:-Make-evidence-BAMs) for more details.

Dan

**Comment by dancooke** [comment]
Closing this - please re-open if any further help needed.
