### ISSUE TITLE
libhts.so.2 not found

### ISSUE THREAD

**Issue by oskarvid** [luntergroup/octopus#3]
I compiled the latest octopus and got this error:
`octopus: error while loading shared libraries: libhts.so.2: cannot open shared object file: No such file or directory`
I followed the instructions in the README.md but something seems to be broken. 
To be more precise, I'm trying to install octopus in a docker image using Ubuntu 16.04 as a base image.

Here are the exact lines of code that I used inside of an Ubuntu 16.04 container:
`apt-get update && apt-get -y install clang-3.8 libstdc++6 libboost-all-dev cmake wget git-all zlib1g-dev python3 autoconf`
`git clone https://github.com/samtools/htslib.git && cd htslib && autoheader && autoconf && ./configure && make -j4 && make install && cd /`
`git clone https://github.com/luntergroup/octopus.git`
`cd /octopus/build && cmake -D CMAKE_C_COMPILER=clang-3.8 -D CMAKE_CXX_COMPILER=clang++-3.8 -DINSTALL_ROOT=ON .. && make install`
I have also tried using python to install octopus, but I got the same error message. 

What could be the problem? 
/Oskar

**Comment by dancooke** [comment]
Hi Oskar,

This is because `/usr/local/lib` (where htslib installs to by default) is not in the standard library paths, probably because this is a fresh Ubuntu installation and no other libraries has been installed there yet. You can add it *after* installing htslib by running the command:

``
$ ldconfig /usr/local/lib
``

You can read more about this [here](http://unix.stackexchange.com/questions/67781/use-shared-libraries-in-usr-local-lib).

Dan

**Comment by oskarvid** [comment]
Thanks, it works now!

There's another thing I thought I should mention. As I was trying to fix this bug myself yesterday, I saw that on line 63 in FindHTSlib.cmake, it says  $ENV{HTLSIB_ROOT}, but shouldn't it be  $ENV{HTSLIB_ROOT}? I edited it and recompiled yesterday, and nothing changed, so maybe it's not critical? I don't know, but I wanted to let you know either way.

Cheers!
/Oskar

**Comment by dancooke** [comment]
Thanks Oskar, that certainly looks like a typo! BW, Dan
