### ISSUE TITLE
Genotype GT and Phasing

### ISSUE THREAD

**Issue by ChristopheLegendre** [luntergroup/octopus#32]
@dancooke 
label:question

Hi Daniel,

I have installed 0.4.1-alpha Octopus using miniconda and run it in the tumor-normal somatic mode
I have looked at the VCF and at the GT field in particular. I am a little bit befuddled when looking at the GT field for the tumor. I often see four (4) values in the GT, for instance: 

`#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  NORMAL    TUMOR` 

` 22      18847497        .       CA      C       3       DP;FRF;GQ;MQ    AC=1;AN=6;DP=2;MP=24.22;MQ=28;MQ0=0;NS=2;SOMATIC        GT:GQ:DP:MQ:PS:PQ:VAF_CR:FT     0|0:1:1:31:18847497:31:.,.:GQ,DP        **0|0|1|0**:1:1:25:18847497:31:0.01,0.42:GQ,MQ,DP,FRF  ` 
` 22      18847501        .       A       C       14.52   DP;GQ;MQ        AC=1;AN=6;DP=3;MP=24.22;MQ=27;MQ0=0;NS=2;SOMATIC        GT:GQ:DP:MQ:PS:PQ:VAF_CR:FT     0|0:5:1:31:18847497:31:.,.:GQ,DP        **0|0|0|1**:5:2:25:18847497:31:0.09,0.64:GQ,MQ,DP    `  
` 22      18847511        .       A       C       16.98   DP;FRF;GQ;MQ    AC=1;AN=6;DP=4;MP=24.22;MQ=28;MQ0=0;NS=2;SOMATIC        GT:GQ:DP:MQ:PS:PQ:VAF_CR:FT     0|0:4:2:31:18847497:31:.,.:GQ,DP        **0|0|0|1**:4:2:25:18847497:31:0.09,0.64:GQ,MQ,DP,FRF   `  
 
 
I read the paragraph  << _*Why do octopus VCF files contain * and .?*_ >> in the user manual, but I am still confused about GT representation in Octopus' vcf file. [ using --legacy did not fix that confusion ].  
I understand the phasing, but not the values. 
Here we can see that positions 501 and 511 have been phased together and are in the the phase whereas 497 is not in the same phase block;  
What I do not understand in that example is why we have three (3) zeros.  
I added a _screenshot of IGV_ for the region given as an example above;  Based on that example, I would have expected GT=0|1 in the Tumor and not 0|0|0|1 for positions 501 and 511. 

**__note__**: These calls examples are just examples purposes.  In real conditions, these calls would be filtered out from our final list of variants.

### Here my questions
1. Could you explain in further details, the Octopus specifications for the GT field, and in the 0|0|0|1 and 0|0|1|0 in the example above in particular? 
2. If all the calls contains a PS value, does that mean that if a call has a PS value that is unique across the VCF file, that call was actually not phased with any other call and therefore should not have a pipe character but a slash character in the GT? 
3. If it is not phased, can Octopus not adding the PS field in the unphased variants (smaller VCF), and keep it of course in the phased calls?  
4. Does `--legacy` option only impact the GT field by converting some "0" to dot (".") in that field, or does it also impact other fields in the VCF? 

Thanks for helping the community understanding Octopus better.
Best, 
Chris

![octopus_call_4gt anno](https://user-images.githubusercontent.com/2623980/44881850-f9f41f00-ac65-11e8-9eea-9fc262e448e4.png)

**Comment by dancooke** [comment]
Hi Chris,

Thanks for the questions.

> Could you explain in further details, the Octopus specifications for the GT field, and in the 0|0|0|1 and 0|0|1|0 in the example above in particular?

The meaning of the `GT` fields with regards to `SOMATIC` calls (and their phase partners) is explained [here](https://github.com/luntergroup/octopus/wiki/Calling-models:-Cancer). Essentially octopus always tags on somatic haplotypes onto the germline genotype. In your example, 0|0|0|1  means the germline is called homozygous reference (**0|0**|0|1 ), two unique somatic haplotypes were called, one has the reference allele at this site (0|0|**0**|1 ), and the other has the first `ALT` (0|0|0|**1** ). The benefit of this notation, rather than just reporting `0/1` is that we can see the phase of somatic mutations with respect to both germline variants and other somatic mutations.

Unfortunately it looks like this region has been miscalled so it's not a very good demonstration of this capability. Also, I think v0.5-beta will do a better job of calling this region as it will specifically check for these fairly common cases SNV misalignments in microsatellites.

> If all the calls contains a PS value, does that mean that if a call has a PS value that is unique across the VCF file, that call was actually not phased with any other call and therefore should not have a pipe character but a slash character in the GT?

Yes this is correct. Although Octopus is not making an incorrect claim here; a call is only phased if it shares a `PS` with another call.

> If it is not phased, can Octopus not adding the PS field in the unphased variants (smaller VCF), and keep it of course in the phased calls?

I have considered making this change previously. The main reasons for not doing it so far are: 1) Consistency. 2) Octopus reconstructs called haplotypes in the VCF for filtering, this reconstruction currently expects phase information for every VCF line. I don't think the second would be too hard to resolve, and the space saving argument you make is certainly a good one - I'll probably do this at some point.

> Does --legacy option only impact the GT field by converting some "0" to dot (".") in that field, or does it also impact other fields in the VCF?

No, the `--legacy` option just strips out the `*`s and `.`s from `GT` and `ALT` (just `*`) fields.

Hope that helps.

Best,
Dan

**Comment by ChristopheLegendre** [comment]
Hi Dan,

Thanks for your reply.

After reading the Wiki and reading your reply, I definitely have a much better understanding of the genotype representation in Octopus' VCF.  

As I downloaded the user manual first, I totally forgot to look in the Wiki pages which seems to have more and further explanations for some topics than the User Manual.

I am fine with having `PS` in all lines and understand the need for consistency; I merely suggested it for file size reasons because with an increased number of samples in the VCF, the amount of redundant information might lead to a rapid increase of the file size.


**follow up question related to genotype**:     [_NOTE: do you want me to open the following issue kind of related to genotype as a bug report? _]
Due to the way Octopus represents the genotype in the somatic calls, tools that rely on having only 2 values in the GT fields or tools that rely on a certain order for indexing VCF may fail.  For instance, I tried to bgzip and  tabix on a sorted vcf using vcftools ; 
Indexing vcf is mainly used by bcftools and igv. It increases speed access to information for big vcf files.

For instance, I got the following error message:
`tabix -p vcf vcf.vcf.gz ` 
`[E::get_intv] Failed to parse TBX_VCF, was wrong -p [type] used?  ` 
` The offending line was: "22      16050933        .       G       A       18.38   PASS    AC=2;AN=4;DP=6;MQ=38;MQ0=0;NS=2 GT:GQ:DP:MQ:PS:PQ:FT    1|0:18:2:27:16050933:99:PASS    1|0:18:4:42:16050933:99:PASS" ` 
` [E::get_intv] Failed to parse TBX_VCF, was wrong -p [type] used?  ` 
` The offending line was: "22      16051249        .       T       C       6.62    q10     AC=4;AN=4;DP=1;MQ=60;MQ0=0;NS=1 GT:GQ:DP:MQ:PS:PQ:FT    1|1:3:0:0:16051249:99:q10       1|1:3:1:60:16051249:99:q10" .  ` 
` [E::hts_idx_push] Unsorted positions on sequence #4712259: 1 followed by 0
tbx_index_build failed: vcf.vcf.gz `  


**Question**
1. Do you know a tool that is able to index the Octopus VCF files? 

Thanks,
Best,
Chris

**Comment by dancooke** [comment]
Hi Chris,

There should be no problem compressing and indexing Octopus VCFs (either the native output ones or the `--legacy` generated ones). In fact, Octopus automatically generates and indexes `.vcf.gz` and `.bcf` files if the `--output` has either of these respective extensions.

In other words: If you are having problems indexing an Octopus VCF then it is a bug rather than a problem with the format used by Octopus; Octopus' default VCF representation fully conforms to VCF spec 4.3. If you've passed Octopus' VCF through `vcftools` then it's also possible there is a problem with vcftools.

Best,
Dan

**Comment by ChristopheLegendre** [comment]
Hi Dan,

The issue was with the VCF file itself; After discussing with coworker who created the VCF file, it happened that the vcf got created from a copy/paste and therefore got malformed on one line which is at the origin of the error. 
I usually run vcf-validator on my vcf but did not this time and therefore misled me on the type of error raised by tabix.    _Sorry about that_.
 
After modifying the VCF, everything worked fine and tabix did create the index.

Thanks.
Best,
Chris.
