### ISSUE TITLE
Output realigned BAM files in Cancer Somatic Mode

### ISSUE THREAD

**Issue by ChristopheLegendre** [luntergroup/octopus#33]
@dancooke 
possible label:enhancement

Hi Daniel,

**Question:** 
1. Would it be possible to get **_Output realigned BAM files_** for both Normal and Tumor samples when using Octopus in Somatic mode (aka Cancer Mode)?

Thanks,
Best,
Chris.

**Comment by dancooke** [comment]
Hi Chris,

This feature has been added to the upcoming v0.5-beta (along with lots of other improvements). I haven't yet implemented 'split' realigned BAMs for multi-sample calling though - I'm aiming to do this at some point, but probably not in time for v0.5-beta.

Best,
Dan

**Comment by ChristopheLegendre** [comment]
Hi Dan,

Thanks for the reply.
**Question:** 
1. Any E.T.A for the next v0.5 version?

Best,
Chris.

**Comment by dancooke** [comment]
Hi Chris,

It's in the final rounds of testing; I'm not planning on making any more significant changes, so if everything goes smoothly then I'd say about a week.

Also, it turned out to be pretty simple to implement 'split' realigned BAMs for multi-sample calling, so that will make it into v0.5-beta after all!

Cheers,
Dan

**Comment by ChristopheLegendre** [comment]
Hi Dan,

That is great news !
A week to go and ... with split realigned bam for Tumor-Normal Somatic Model!  :+1:  :+1:  
I will be glad to test it out, in my case mostly with `Cancer Model` in __Somatic Mode__, but also with multiple tumor samples from same individual.

Thanks,
Best,
Chris
