### ISSUE TITLE
Realigned BAM not sorted

### ISSUE THREAD

**Issue by ChristopheLegendre** [luntergroup/octopus#35]
@dancooke 

Hi Dan,

After successfully installing `version 0.5.0-Beta` (see my after-closed issue reply in #30), I have run the tool in the "tumor-normal somatic" mode with the --bamout option added to the command line.
Two bam files got generated but only one has been indexed, the normal bam.

I tried manually to indexed the Tumor BAM file, but failed because the BAM was not sorted properly. I sorted it manually and then successfully indexed it.

**_Question_**:  Would it be possible to have Octopus automatically sorting and indexing the Tumor Realigned BAM file as well or any other realigned bam files?

Thanks,
Chris

**Comment by dancooke** [comment]
Hi Chris,

Thanks for opening an issue on this. I am aware of this problem, but unfortunately haven't had the time to try to resolve it yet, and I didn't want to delay v0.5.0-beta any longer.

The problem is not specifically to do with tumour BAMs; Octopus doesn't distinguish samples in any way when realigning BAMs - it just considers the called genotypes. I think the problem is linked to the way Octopus realigns reads in blocks that correspond to phase sets.

I'll try to resolve this as soon as possible, but my focus is on finishing a manuscript for Octopus now, so it might be a few weeks.

Thanks,
Dan

**Comment by ChristopheLegendre** [comment]
@dancooke 
Hi Dan,

Thanks for your reply; I noticed the issue when I tried to load the BAM file in IGV;
Just wanted to give feedback and make users aware of it. 
No rush; The user can still manually sort and index the bam files ;-) :-) 

Wish you well with the manuscript.

Best,
Chris

**Comment by dancooke** [comment]
I think that I've fixed this in f0b49cfbeddcbe1e21ce9dba202947feb28624fe, which is available on the develop branch and will appear in the next release. Please re-open if any further issues.
