### ISSUE TITLE
Reducing runtime by a scatter/gather approach ?

### ISSUE THREAD

**Issue by af8** [luntergroup/octopus#53]
Hi,

Just a very quick and generic question.

Although it is not mentioned explicitly in the docs, I suppose that splitting the analysis into several genomic intervals and then merging VCFs is a good approach to reduce runtime or is there any reason you would not recommend that with your tool ?

Thanks,
Anthony

**Comment by dancooke** [comment]
Hi Anthony,

This is essentially the approach taken by the `--threads` option. It is not guaranteed that results from `split-and-merge` will be identical to calling an entire contig due to the haplotype nature of the calling algorithm (positions are not independent). This is not usually a big issue for short Illumina reads, unless the contig is split on or near to a complex variant (e.g. a large indel).

I would recommend using the `--threads` option if possible for a few reasons:

- Octopus tries to address the problem mentioned above with `split-and-merge` by looking for conflicting haplotypes from adjacent regions and recalling if necessary.
- Octopus should be able to do a better job of thread load balancing than you can do manually.
- It's less work for you.

You can read more about the `--threads` option [here](https://github.com/luntergroup/octopus/wiki/How-to:-Use-multiple-threads).

Cheers
Dan

**Comment by dancooke** [comment]
I'll close this. Note that [v0.6.3-beta](https://github.com/luntergroup/octopus/releases/tag/v0.6.3-beta) improved runtime considerably for somatic calling.
