### ISSUE TITLE
MAP_VAF in Cancer Calling Model

### ISSUE THREAD

**Issue by JesseDGibson** [luntergroup/octopus#81]
Hi, I had a couple questions about the MAP_VAF field under the cancer calling model. I'm currently running octopus on targeted non-human sequencing data with the --very-fast flag and focusing on a subset of the targeted regions using the -t flag for testing. I'm running the cancer calling model in tumor only mode because I'm interested in calling somatic variants in normal tissue where there isn't a great normal control to compare against. For the calls that are labelled as somatic in the output, I had two questions about the MAP_VAF field. 

For variants that have several alternate alleles, the MAP_VAF field only shows a single value (and the VAF_CR one interval) - how should this value be interpreted? Is it the total frequency of all alternate alleles, just the lowest frequency, just the highest? Is there a way to get allele frequencies for all alternate alleles individually?

Also, I was curious about the distribution of reads supporting all of the calls so I added --annotations AF to force the alternate allele fraction to be output - here I noticed that some of the VAF_CR intervals may be very tight seemingly indicating high confidence and yet the AF and MAP_VAF fields may have very different values. For instance in one call I have MAP_VAF=0.8, VAF_CR=(0.77,0.82) but AF=0.505, and the coverage depth here is fairly high (INFO/DP=684) and both the FILTER and FMT/FT filters are PASS. I imagine this has something to do with how the a posteriori probabilities are calculated but it seems weird for the two values to be so different - does this seem normal?

Thanks

**Comment by dancooke** [comment]
Hi Jesse,

> For variants that have several alternate alleles, the MAP_VAF field only shows a single value (and the VAF_CR one interval) - how should this value be interpreted? Is it the total frequency of all alternate alleles, just the lowest frequency, just the highest? Is there a way to get allele frequencies for all alternate alleles individually?

Both refer to the called somatic allele with maximum MAP VAF. This should definitely be changed to report one value per called somatic allele - it's on the todo list (I'll leave this issue open until done as a reminder).

> Also, I was curious about the distribution of reads supporting all of the calls so I added --annotations AF to force the alternate allele fraction to be output - here I noticed that some of the VAF_CR intervals may be very tight seemingly indicating high confidence and yet the AF and MAP_VAF fields may have very different values. For instance in one call I have MAP_VAF=0.8, VAF_CR=(0.77,0.82) but AF=0.505, and the coverage depth here is fairly high (INFO/DP=684) and both the FILTER and FMT/FT filters are PASS. I imagine this has something to do with how the a posteriori probabilities are calculated but it seems weird for the two values to be so different - does this seem normal?

Doesn't sound normal. Which version of Octopus are you running? There have been some bug fixes to some of the 'allele depth' type calculations since v0.6.0b. Otherwise, is this for a record with multiple `ALT` alleles?

**Comment by dancooke** [comment]
One possible explanation is that large number of reads were filtered for calling (and therefore not used to compute `MAP_VAF` & `VAF_CR`). Unless the [`--use-calling-reads-for-filtering`](https://github.com/luntergroup/octopus/wiki/Command-line-reference#command---use-calling-reads-for-filtering) is used (not recommended), most read filters are disabled for variant filtering. Since the annotations requested with [`--annotations`](https://github.com/luntergroup/octopus/wiki/Command-line-reference#option---annotations) are computed during filtering, noticeable differences in similar looking statistics can arise. One way to check this is to request the `FRF` (Filtered Read Fraction) annotation.

On the missing `AD` and `ADP` annotations. This occurs if the annotations are not used for variant filtering. How are you filtering your variants? If you use [random forest filtering](https://github.com/luntergroup/octopus/wiki/Variant-filtering:-Random-Forest) (recommended) then all annotations can be requested.

**Comment by dancooke** [comment]
The default filter only trigger the `FRF` FILTER if `FRF > 0.5`, so this doesn't mean my explanation couldn't be correct. Let's see what the `FRF` annotations are...

Probably the provided somatic random forest wouldn't be appropriate for such high depth data. You don't need well known variants (e.g. dbSNP) for training the forest, just a truth set. You can simulate your own truth set but it isn't easy to do this well. So probably you'll just need to stick with the default filters for now.

A note on your options. `--max-somatic-haplotypes 100` is way too high - actually the genotype model will currently only allow up to 10 haplotypes in total (so 8 somatic haplotypes given diploid germline). The tumour would need to have an extremely high mutation rate and substantial subclonality (e.g. neutrally evolving) to have even 8 local somatic haplotypes. Also, `--max-genotype 100` is very low - this doesn't leave much room for error in the heuristics used to determine which genotypes to keep for modelling. I'd suggest at-least a value of 1000.

**Comment by dancooke** [comment]
If you add `--debug` to your command and send the resulting log file then I can tell you which filters are being triggered.

**Comment by JesseDGibson** [comment]
Awesome, thanks! Here's the logfile after running the same command but adding `--debug `
[octopus_debug.log](https://github.com/luntergroup/octopus/files/3553070/octopus_debug.log)
I took a quick peek (granted, I don't know what I'm looking for) and at least for the first region it looks like a lot of them were marked as duplicates during the preprocessing I did, which makes some sense but do you think that would account for differences between `AF` and `MAP_VAF`?

**Comment by dancooke** [comment]
You're right - a lot of reads are being filtered due to being marked duplicate duplicates. This could in principle explain the difference between `AF` and `MAP_VAF`. To confirm, would you be able to generate a realigned BAM file (i.e. using the `--bamout` option), and send a sub-bam containing just the reads overlapping one of the variants that show this discrepancy?

**Comment by JesseDGibson** [comment]
Hi Dan, sorry it took me a bit to get back to you. I ran octopus again with the same command but adding in the `--bamout` option. I picked out one variant that still looks strange, the VCF line is here

`dd_Smes_g4_10   5053294 .       A       T       10000   PASS    AC=1;AN=3;DP=2098;MQ=59;MQ0=0;NS=1;PP=510.31;SOMATIC   GT:GQ:DP:MQ:PS:PQ:MAP_VAF:VAF_CR:AF:FRF:FT  0|0|1:510:2098:59:5053294:99:0.9:0.89,0.91:0.430:0.454:PASS`

And [here is a link](https://drive.google.com/open?id=1aT293zhzBPiHRW6ssnaJ7u2oisnlNaQS) (github wouldn't let me upload bam in this comment) to a portion of the bamout file that overlaps, extracted using 
`samtools view -b -h -o ./Alignments/weird_variant_10_5053294.bam ./Alignments/octopus_chr10_EX2.bam dd_Smes_g4_10:5053294`

Thanks!

**Comment by dancooke** [comment]
Sorry I didn't realise this was a non-standard reference. Can you send it to me or tell me where I can download it? Cheers.

**Comment by JesseDGibson** [comment]
Here's a [link](https://drive.google.com/file/d/1LCpfc4hvDhQl3o3sutzOEI4GRi-vTBh0/view?usp=sharing) to the reference

**Comment by dancooke** [comment]
Thanks. I believe that Octopus is misclassifying some of the variants this region - there doesn't appear to be any somatic variants. I'm still trying to determine why this is happening.

**Comment by JesseDGibson** [comment]
Huh, that's weird. Is there anything else I could share with you to help figure out what's going on?

**Comment by dancooke** [comment]
Almost a year later... I tried the latest develop branch of Octopus on this data and everything seems to be in working order now. The variant [mentioned](https://github.com/luntergroup/octopus/issues/81#issuecomment-527585854) is now being called heterozygous germline as expected. Of the called somatic variants, which appear to be artefacts and are filtered anyway - the `MAP_HF` is matching up with the `AF`. Note that `MAP_VAF` is now called `MAP_HF` since this statistic refers to haplotypes, not alleles; there is one entry per column in the `GT` field, unlike `AF` which has one entry per allele.
