### ISSUE TITLE
question about levels of phasing

### ISSUE THREAD

**Issue by ChristopheLegendre** [luntergroup/octopus#84]
label: question

Hi Dan,

Besides the difference in speed you mentioned in another issue, what are the differences between minimal, conservative, moderate, normal, and aggressive values for the option `--phasing-level`?  

Thanks,
Chris

**Comment by dancooke** [comment]
Hi Chris,

Please see the documentation for the option [`--lagging-level`](https://github.com/luntergroup/octopus/wiki/Command-line-reference#option---lagging-level), which has replaced `--phasing-level`.

Dan

**Comment by ChristopheLegendre** [comment]
Hi Dan,
Thanks for the quick reply.
I will replace `--phasing-level` with `--lagging-level` ; 
Does that mean `--phasing-level` is going to be deprecated?

**Comment by dancooke** [comment]
Sorry I should have said "renamed" - I decided to rename it since "phasing"-level was a bit misleading (it doesn't really *directly* control phasing), plus it makes the relationship with the other haplotype generation options ([`--extension-level`](https://github.com/luntergroup/octopus/wiki/Command-line-reference#option---extension-level) and ['--backtrack-level`](https://github.com/luntergroup/octopus/wiki/Command-line-reference#option---backtrack-level)) clearer.

**Comment by ChristopheLegendre** [comment]
Are these options `--backtrack-level` and `--lagging-level` available in version  0.6.3-beta?
I do not see them when I run `octopus/0.6.3-beta/octopus  --help` or will they be present in the next release onward.

**Comment by dancooke** [comment]
No - they’re not in v0.6.3-beta. They’re available on the development branch and will be in the next release onwards. There are quiteba few other command line changes coming in the next release - I’ll document them all in the release notes.

**Comment by ChristopheLegendre** [comment]
Thanks Dan.
